#include "connection.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "transport.h"

static const char *kMsg = "HELLO WORLD!";

// Given a message and starting at start_index, return number of bytes to send.
static int bytes_to_send(const char *message, int start_index) {
    int bytes = 2 + rand() % (10 - 2 + 1);
    if (start_index + bytes - 1 >= (int)strlen(message)) {
        bytes = (int)strlen(message) - start_index;
    }
    printf("generated bytes to send: %d\r\n", bytes);
    return bytes;
}

void client_handle_timeout(connection_t *connection) {
    switch (connection->state) {
        case ESTABLISHED:
            printf("timeout during data send! Resending last packet, seq num %u\n", connection->curr_seq);
            break;
        default:
            printf("Timeout during handshake!\n");
            connection->state = CLOSED;
            break;
    }
}

void client_handle_state(connection_t *connection, tcp_packet_t packet, int socket_id,
                         struct sockaddr_in server_addr, socklen_t server_addr_len) {
    switch (connection->state) {
        case SYN_SENT:
            // if server responds with SYN_ACK, send ACK and transition to ESTABLISHED.
            // else, close connection and exit.
            if ((packet.flags & (FLAG_SYN | FLAG_ACK)) == (FLAG_SYN | FLAG_ACK) &&
                packet.ack == connection->curr_seq) {
                printf("Received SYN_ACK!\n");
                connection->next_expected = packet.seq_num + 1;
                connection->state = ESTABLISHED;
                tcp_packet_t ack_packet;
                memset(&ack_packet, 0, sizeof(ack_packet));
                ack_packet.flags = FLAG_ACK;
                ack_packet.seq_num = connection->curr_seq;
                ack_packet.ack = connection->next_expected;
                int result = send_packet(ack_packet, socket_id, &server_addr, server_addr_len);
                if (result != 0) {
                    fprintf(stderr, "Failed to send ACK packet\n");
                    return;
                }
                // Do NOT update curr_seq since ACK does not consume sequence number
                printf("Sent ACK packet with seq_num: %u and ack: %u\n", ack_packet.seq_num, ack_packet.ack);
                printf("Connection established!\n");

                // Connection established. Send first data packet.
                tcp_packet_t data_packet;
                memset(&data_packet, 0, sizeof(data_packet));
                data_packet.flags = FLAG_DAT;
                data_packet.seq_num = connection->curr_seq;
                int start = (int)(connection->curr_seq - connection->initial_seq - 1);
                int data_len = bytes_to_send(kMsg, start);
                memcpy(data_packet.payload, kMsg + start, data_len);
                data_packet.payload_len = data_len;
                result = send_packet(data_packet, socket_id, &server_addr, server_addr_len);
                if (result != 0) {
                    fprintf(stderr, "Failed to send data packet\n");
                    return;
                }
                printf("sent data packet with seq_num: %u\n", data_packet.seq_num);
                connection->curr_seq += data_len;
            } else {
                fprintf(stderr, "Failed to establish connection: expected SYN-ACK packet\n");
                return;
            }
            break;
        case ESTABLISHED:
            // if receive expected ack within timeout, send next packet.
            // Else, resend.
            printf("Received packet with seq_num: %u and ack: %u\n", packet.seq_num, packet.ack);
            printf("curr_seq: %u, next_expected: %u\n", connection->curr_seq, connection->next_expected);
            if ((packet.flags & FLAG_ACK) == FLAG_ACK && packet.ack == connection->curr_seq) {
                printf("Received ACK for data packet!\n");
                // send next string.
                // Otherwise, if sent last string, close connection.
                if (connection->curr_seq == connection->initial_seq + 1 + strlen(kMsg)) {
                    printf("All packets fully ACK'd! Sending FIN.\n");
                    tcp_packet_t fin_packet;
                    memset(&fin_packet, 0, sizeof(fin_packet));
                    fin_packet.flags = FLAG_FIN;
                    fin_packet.seq_num = connection->curr_seq;
                    int result = send_packet(fin_packet, socket_id, &server_addr, server_addr_len);
                    if (result != 0) {
                        fprintf(stderr, "Failed to send FIN packet\n");
                        return;
                    }
                    connection->state = FIN_SENT;
                    connection->curr_seq += 1;
                } else {
                    // send packet. increment curr_seq, last_sent_index
                    printf("Sending next data!\n");
                    tcp_packet_t data_packet;
                    memset(&data_packet, 0, sizeof(data_packet));
                    data_packet.flags = FLAG_DAT;
                    data_packet.seq_num = connection->curr_seq;
                    int start = (int)(connection->curr_seq - connection->initial_seq - 1);
                    int data_len = bytes_to_send(kMsg, start);
                    memcpy(data_packet.payload, kMsg + start, data_len);
                    data_packet.payload_len = data_len;
                    int result = send_packet(data_packet, socket_id, &server_addr, server_addr_len);
                    if (result != 0) {
                        fprintf(stderr, "Failed to send data packet\n");
                        return;
                    }
                    printf("sent data packet with seq_num: %u\n", data_packet.seq_num);
                    connection->curr_seq += data_len;
                }
            } else {
                fprintf(stderr, "Received invalid ack!\n");
            }
            break;
        case FIN_SENT:
            // if receive ACK for FIN, transition to CLOSED. Else, resend FIN.
            if ((packet.flags & FLAG_ACK) == FLAG_ACK && packet.ack == connection->curr_seq) {
                printf("Received ACK for FIN, connection closed!\n");
                connection->state = CLOSED;
            } else {
                fprintf(stderr, "Failed to receive ACK for FIN!\n");
            }
            break;
        default:
            // should not reach here
            break;
    }
}

void server_handle_state(connection_t *connection, tcp_packet_t packet, int socket_id,
                         struct sockaddr_in client_addr, socklen_t client_addr_len,
                         char *buffer, size_t buffer_size) {
    (void)buffer_size;
    switch (connection->state) {
        case CLOSED:
            // if packet is SYN, respond with SYN_ACK and transition to SYN_RECEIVED.
            if (packet.flags & FLAG_SYN) {
                connection->next_expected = packet.seq_num + 1;

                tcp_packet_t syn_ack_packet;
                memset(&syn_ack_packet, 0, sizeof(syn_ack_packet));
                syn_ack_packet.flags = FLAG_SYN | FLAG_ACK;
                syn_ack_packet.seq_num = connection->curr_seq;
                syn_ack_packet.ack = connection->next_expected;
                serialize_packet(syn_ack_packet, buffer);
                int result = send_packet(syn_ack_packet, socket_id, &client_addr, client_addr_len);
                if (result != 0) {
                    fprintf(stderr, "Failed to send SYN-ACK packet\n");
                    return;
                }
                connection->state = SYN_RECEIVED;
                printf("Sent SYN-ACK packet with seq_num: %u and ack: %u\n", syn_ack_packet.seq_num,
                       syn_ack_packet.ack);
            }
            break;
        case SYN_RECEIVED:
            // if client responds with ACK and ACK is correct, transition to ESTABLISHED.
            // else, close connection and exit.
            if ((packet.flags & FLAG_ACK) == FLAG_ACK && packet.ack == connection->curr_seq + 1) {
                printf("Received ACK, connection established!\n");
                connection->state = ESTABLISHED;
            } else {
                fprintf(stderr, "Failed to establish connection, expected ACK with ack_num: %u\n",
                        connection->curr_seq + 1);
                connection->state = CLOSED;
            }
            break;
        case ESTABLISHED:
            // if packet seq_number not expected, resend previous ack.
            // else, send ACK for packet and process payload.
            if ((packet.flags & FLAG_FIN) == FLAG_FIN) {
                printf("Received FIN from client!\n");
                connection->state = FIN_SENT;

                tcp_packet_t fin_ack_packet;
                memset(&fin_ack_packet, 0, sizeof(fin_ack_packet));
                fin_ack_packet.flags = FLAG_ACK;
                fin_ack_packet.seq_num = connection->curr_seq;
                fin_ack_packet.ack = packet.seq_num + 1;
                serialize_packet(fin_ack_packet, buffer);
                int result = send_packet(fin_ack_packet, socket_id, &client_addr, client_addr_len);
                if (result != 0) {
                    fprintf(stderr, "Failed to send ACK for FIN packet\n");
                    return;
                }
                printf("Sent ACK for FIN with seq_num: %u and ack: %u\n", fin_ack_packet.seq_num,
                       fin_ack_packet.ack);
                connection->curr_seq += 1;
                connection->next_expected += 1;
                connection->state = CLOSED;
            } else if (packet.flags & FLAG_DAT) {
                if (packet.seq_num == connection->next_expected) {
                    printf("received expected packet!\n");
                    connection->next_expected += packet.payload_len;
                    printf("Received data: %.*s\n", packet.payload_len, packet.payload);

                    tcp_packet_t ack_packet;
                    memset(&ack_packet, 0, sizeof(ack_packet));
                    ack_packet.flags = FLAG_ACK;
                    ack_packet.seq_num = connection->curr_seq;
                    ack_packet.ack = connection->next_expected;
                    serialize_packet(ack_packet, buffer);
                    int result = send_packet(ack_packet, socket_id, &client_addr, client_addr_len);
                    if (result != 0) {
                        fprintf(stderr, "Failed to send ACK packet\n");
                        return;
                    }
                    printf("Sent ACK packet with seq_num: %u and ack: %u\n", ack_packet.seq_num,
                           ack_packet.ack);
                } else {
                    fprintf(stderr,
                            "Received out of order packet. Expected seq_num: %u but got seq_num: %u\n",
                            connection->next_expected, packet.seq_num);
                }
            }
            break;
        default:
            // should not reach here
            break;
    }
}
